// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AngelPerezIntegra.Models
{
    public partial class empleado
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(75)]
        public string apellido { get; set; }
        [Required]
        [StringLength(75)]
        public string nombre { get; set; }
        [Required]
        [StringLength(15)]
        public string telefono { get; set; }
        [Required]
        [StringLength(100)]
        public string email { get; set; }
        [Required]
        [StringLength(150)]
        public string foto { get; set; }
        [Column(TypeName = "date")]
        public DateTime fecha_contratacion { get; set; }
    }
}