// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AngelPerezIntegra.Models;

namespace AngelPerezIntegra.Data
{
    public partial class TestintegraContext : DbContext
    {
        public TestintegraContext()
        {
        }

        public TestintegraContext(DbContextOptions<TestintegraContext> options)
            : base(options)
        {
        }

        public virtual DbSet<empleado> empleado { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=TestIntegra;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<empleado>(entity =>
            {
                entity.HasIndex(e => e.email)
                    .HasName("UQ__empleado__AB6E6164E8FE9426")
                    .IsUnique();

                entity.HasIndex(e => e.telefono)
                    .HasName("UQ__empleado__2A16D9450F0C3A09")
                    .IsUnique();

                entity.Property(e => e.apellido).IsUnicode(false);

                entity.Property(e => e.email).IsUnicode(false);

                entity.Property(e => e.nombre).IsUnicode(false);

                entity.Property(e => e.telefono).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}